# Generated by Django 5.0.6 on 2024-05-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=150)),
                ('email', models.TextField(max_length=200)),
                ('senha', models.TextField(max_length=12)),
            ],
        ),
    ]
